Fix sequence generation in generictest_id_seq
Creating the sequence generictest_id_seq causes a failure:

  ERROR:  syntax error at or near "AS"
  LINE 1: CREATE SEQUENCE "ci-rt".generictest_id_seq AS integer START ...

The AS statement in CREATE SEQUENCE is only available on PostgreSQL
version 10 and newer.

Remove the AS statement to be compatible to PostgreSQL version 9.6.

Fixes: a97ffb7e4095 ("Add generictest entries to database")
Signed-off-by: Benedikt Spranger <b.spranger@linutronix.de>
Signed-off-by: Anna-Maria Gleixner <anna-maria@linutronix.de>